jsStr = {
	common_defaultcurrencyformatpattern               : '#,##0.00',
	common_dateformat                                 : 'dd/MM/yyyy',
	common_integerformatpattern                       : '#,##0',
	common_percentage                                 : '{0}%',
	lblclose                                          : 'Close',
	lblno                                             : 'No',
	lblok                                             : 'OK',
	lblyes                                            : 'Yes',
	rfamessagecode_country_required                   : 'Country/Region is required.',
	rfamessagecode_exists_on_job                      : 'A user by this email has already been submitted to this job.',
	rfamessagecode_ownership_by_duration_cannot_refer : 'An employee has already referred this person to the job. You can refer the person to a job only after the other employee referral becomes inactive.',
	rfamessagecode_email_invalid                      : 'The supplied email is invalid.',
	rfamessagecode_phone_invalid                      : 'The supplied phone number is invalid.',
	rfamessagecode_employee_does_not_have_permissions : 'You do not have permission to submit this referral.',
	rfamessagecode_employee_referral_not_enabled      : 'Referral is not enabled for this company.',
	rfamessagecode_first_name_required                : 'First Name is required.',
	rfamessagecode_invalid_resume_type                : 'The CV is not a valid type. Please upload a different type.',
	rfamessagecode_exceeded_file_size                 : 'The attached file exceeds the size limit. Please attach another file.',
	rfamessagecode_job_req_id_not_valid               : 'There is an issue with the Job, please try another job.',
	rfamessagecode_last_name_required                 : 'Last Name is required.',
	rfamessagecode_phone_number_required              : 'Phone Number is required.',
	rfamessagecode_primary_email_required             : 'Primary Email is required.',
	rfamessagecode_resume_required                    : 'A CV is required.',
	rfamessagecode_success                            : 'Your referral was successfully submitted.',
	rfamessagecode_unknown                            : 'An error occurred while submitting your referral. Please try again later.',
	searchpagetitlenokeyword                          : '{0} Jobs',
	ssopasswordisinvalid                              : 'Password is invalid. Please enter the password you just reset.',
	ssopasswordfailed                                 : 'Sorry, but we could not successfully synchronise your accounts.',
	tcagentalreadyexists                              : 'You already have an alert matching these criteria.',
	tcagentscouldnotbesaved                           : 'Your alerts could not be saved. Please try again.',
	tcalreadyamember                                  : 'Already a member?',
	tcalreadyauserofthissite                          : 'You are already a user of this site.\n\nPlease sign in to manage your profile and alerts.',
	tccheckinput                                      : 'Please check your input.',
	tcconfirminvalid                                  : 'Confirm Password is invalid.',
	tcconfirmisinvalid                                : '{0} is invalid.',
	tcconfirmrequired                                 : 'Confirm Password is required.',
	tccookiesmustbeenabled                            : 'Cookies must be enabled to continue.',
	tcday                                             : 'day',
	tcdays                                            : 'days',
	tcdeletetheseagents                               : 'Are you sure you want to delete these alerts?',
	tcdeletethisagent                                 : 'Are you sure you want to delete this alert?',
	tcemailaddressrequired                            : 'Email address is required.',
	tcemailnotvalid                                   : 'Email is not a valid email address.',
	tcemailrequired                                   : 'Email is required.',
	tcfinishingsubscribe                              : 'Finishing Subscription',
	tcfreqmustbegtone                                 : 'Frequency must be at least 1.',
	tcfreqmustbenumeric                               : 'Frequency must be a number.',
	tcgivenyouapassword                               : 'We have given you a password.',
	tcgivenyouapasswordhelp                           : 'We have already created a password for you.\n\nClicking \'Personalise it?\' allows you to replace the password\nwe created with one of your own.',
	tchelp                                            : 'Help',
	tcjobresultsa11yaccordionchecklabel               : '{0}, {1} results, {2} of {3} items',
	tcjobresultsa11yaccordionsinglechecklabel         : '{0}, 1 result, {1} of {2} items',
	tcjobresultsa11yfiltersearchlabel                 : 'Search {0}',
	tcjobresultsa11yiframetitle                       : 'Google job map',
	tcjobresultsa11yjoblistitem                       : '{0}, {1} of {2}',
	tcjobresultsa11ypagegoto                          : 'Go to page {0}',
	tcjobresultsa11ypagenextlabel                     : 'Go to next page',
	tcjobresultsa11ypagepreviouslabel                 : 'Go to previous page',
	tcjobresultsa11ypageregionlabel                   : 'Pagination',
	tcjobresultsa11ytokenlabel                        : 'Remove {0}',
	tcjobresultsbacktoresults                         : 'Back to Results',
	tcjobresultsclear                                 : 'Clear All',
	tcjobresultscreatejobalertscategorytext           : 'Get Job Alerts for This Category',
	tcjobresultscreatejobalertsdetailstext            : 'Job Alerts Link',
	tcjobresultscreatejobalerttext                    : 'Get Job Alerts for This Search',
	tcjobresultsdropdownrecent                        : 'Most Recent',
	tcjobresultsdropdownrelevant                      : 'Most Relevant',
	tcjobresultserrmaptitle                           : 'The map can\'t display your search results.',
	tcjobresultserrmapsubtitle                        : 'See your results in the list view instead.',
	tcjobresultsfilterheader                          : 'Refine your search',
	tcjobresultsfilterlimitdescription                : 'You can select a maximum of {0} filters. Please unselect some filters to select new ones.',
	tcjobresultsfilterlimittitle                      : 'Filter Limit Reached',
	tcjobresultsfiltersearchplaceholder               : 'Search',
	tcjobresultsheadersortby                          : 'Sort by',
	tcjobresultsheadertitle                           : '{0} to {1} of {2} results',
	tcjobresultssingularheadertitle                   : '1 of 1 results',
	tcjobresultsmoretokes                             : '{0} More',
	tcjobresultsmobileheadersingular                  : '1 Job',
	tcjobresultsmapheader                             : '{0} Jobs Found',
	tcjobresultsmapsingularheader                     : '1 Job Found',
	tcjobresultsmultiplelocations                     : 'Multiple Locations',
	tcjobresultsnocoordinates                         : 'There are no jobs that meet your criteria. Use different search terms or change your filter selections.',
	tcjobresultsnofilterdata                          : 'No information available',
	tcjobresultsnojobsfound                           : 'No jobs found',
	tcjobresultspagenext                              : 'Next',
	tcjobresultspageprevious                          : 'Previous',
	tcjobresultsrefine                                : 'Refine',
	tcjobresultssearchresults                         : 'Search Results',
	tcjobresultsshowless                              : 'Show Less',
	tcjobresultssortbyrecent                          : 'Sort by Most Recent',
	tcjobresultssortbyrelevant                        : 'Sort by Most Relevant',
	tcjobresultsswitchtitle                           : 'Switch between list and map view',
	tcjobresultsswitchmap                             : 'Map View',
	tcjobresultsswitchlist                            : 'List View',
	tcsocialescape                                    : 'If you encounter problems using {0} authentication, or if you do not want to use {0} authentication, you can {linkOpen}fill out the form yourself{linkClose}.',
	tcsocialwaiting                                   : 'Waiting on {0}',
	tclockedout                                       : 'You have exceeded the allowed number of failed logon attempts, and your account has been locked. Please click "Forgot Password?" to reset your password and unlock your account.',
	tcloginfailed                                     : 'Your logon attempt has failed. Please check that your email and password have been entered correctly.',
	tcmhomepage                                       : 'home page',
	tcminvalidemailmessage                            : 'Please enter a valid email address.',
	tcmjobpage                                        : 'job page',
	tcmloggedin                                       : 'You have been logged on as',
	tcmloginfailed                                    : 'If you have forgotten your password, please click the Non-mobile version link below, and then click Forgot Password?',
	tcmpleasesignin                                   : 'Please log on to access your profile.',
	tcmsave                                           : 'Save',
	tcmustprovidekeywordorloc                         : 'You must provide a Keyword, Location or both.',
	tcnotvalidemail                                   : '{0} is not a valid email address.',
	tcnotvalidurl                                     : '{0} is not a valid {1} URL.',
	tcpasswordconfirmmustmatch                        : 'Password and Confirm Password must match.',
	tcpasswordrequired                                : 'Password is required.',
	tcpasswordtoolong                                 : 'Your password is too long.',
	tcpasswordtooweak                                 : 'Password is too weak.',
	tcpasswordvalid                                   : 'Password is valid.',
	tcpasswordvalidmatches                            : 'Password is valid and matches.',
	tcpasswordsdonotmatch                             : 'Passwords do not match.',
	tcpersonalizeit                                   : 'Personalise it?',
	tcpleasecheckyourinput                            : 'Please check your input.',
	tcpleasewait                                      : 'Please wait...',
	tcprivacypolicyoutofdate                          : 'You must review the most recent version of the Data Privacy Consent Statement.',
	tcprofilecantbesaved                              : 'Your profile could not be saved. Please try again.',
	tcprofileinvalidagent                             : 'We cannot save your alert because it is invalid.',
	tcpwconfirmmatch                                  : 'Password and Confirm must match.',
	tcpwhasbeenreset                                  : 'If an account matches the email address you entered, then you will receive an email with instructions on how to reset your password. Each time you reset your password, all previous password reset links in emails will be disabled.',
	tcpwrequirements                                  : 'Passwords must match and be {0}-20 characters in length, and must also contain:\n   - at least one alpha character\n   - at least one number or special character\n   - no more than three repeating characters',
	tcpwresetsuccess                                  : 'Your password was successfully reset.',
	tcredirectingtojob                                : 'Redirecting to Job',
	tcremembermehelp                                  : 'Choosing Remember Me sets a permanent cookie on your machine\nand should not be used on public or shared computers.',
	tcresetpasswordemail                              : 'Please enter a valid email above.',
	tcreviewprivacypolicy                             : 'The Data Privacy Consent Statement must be reviewed.',
	tcsavingagents                                    : 'Saving Alerts',
	tcsavingprofile                                   : 'Saving Profile',
	tcsorry                                           : 'Sorry!',
	tcsorrygenericerror                               : 'Sorry, an error occurred. Please try again.',
	tcsuccess                                         : 'Success!',
	tctoskipenablecookies                             : 'To skip this step in the future, make sure cookies are enabled.',
	tcusernotinsystem                                 : 'The user doesn\'t exist in our system.',
	tcvalidateisrequired                              : '{0} field is required.',
	tcyoudonthaveagents                               : 'You do not have any alerts.',
	tcyouhavemaxagentsallowed                         : 'You already have the maximum number of alerts allowed.',
	pageexpiredmessage                                : 'We\'re sorry, the page you are trying to access has expired.',
	tcnumberofresultsmultiplepages                    : '{0} of {1} jobs found',
	tcnumberofresultssinglepage                       : '{0} jobs found',
	tcnojobsfoundforsearch                            : 'We couldn\'t find any jobs that match.',
	tcnojobsfoundforsearchsubtitle                    : 'Double-check your spelling or consider using a different term, then try again.',
	tcerrorinprocessingsearch                         : 'We can\'t process your search request at this time.',
	tconejobfound                                     : '1 job found',
	tlpnoresultsattention                             : 'There are currently no open positions matching this category or location.',
	lblaccept                                         : 'Accept',
	lblbrowse                                         : 'Browse',
	lblok                                             : 'OK',
	skillmatchingskillpanelhelp                       : 'Let the system review your CV so we can show you a list of recommended jobs based on your skills. We don\'t keep or save your CV, so you\'ll need to upload it in a separate step when you\'re ready to actually apply.',
	tcjobresultsmapnotavailablelabel                  : 'The map view is not available with Skills Matching',
	tcjobresultsrecommendedjobtitle                   : 'Recommended Jobs',
	tcjobresultsskillmatchedlabel                     : 'Skill Matched',
	skillmatchingskillpanelheadertitle                : 'Skills Matching',
	skillmatchingskillpaneltext                       : 'Find your next role!',
	skillmatchingskillpanelmyskillstext               : 'My Skills',
	skillmatchingskillpanellabel                      : 'Use your CV to find the jobs that best match your skills',
	skillmatchingskillpanelgettingstartedbuttontext   : 'Get Started',
	skillmatchingdialogdpcscountrylabel               : 'Country/Region of Residence',
	skillmatchingdialogdpcscountryplaceholder         : 'Select Country/Region',
	skillmatchingdialogviewjobtext                    : 'View Jobs',
	skillmatchingdialogmatchskillstext                : 'Match Skills',
	skillmatchingdialogresumeuploaddesc               : 'Upload a CV so we can recommend jobs that match your skills. We’ll only use it to identify your skills, then delete it. It isn’t saved and it’s not connected to your application',
	skillmatchingdialogresumelabel                    : 'CV',
	skillmatchingdialogfiletypeslabel                 : 'Accepted file types: DOCX, PDF and text',
	skillmatchingdialogfilesizelimit                  : 'File size limit: 3 MB',
	skillmatchingdialoguploadplaceholder              : 'Browse or drop a file',
	skillmatchingdialogresumecheckedlabel             : 'CV Checked',
	skillmatchingdialogresumeremovefilelabel          : 'Remove File',
	skillmatchingdialogresumeuploadinglabel           : 'Identifying skills in your CV',
	skillmatchingdialogyourskillswithcountlabel       : 'Your Skills ({0})',
	skillmatchingdialogmanagemyskillswithcountlabel   : 'View My Skills ({0})',
	skillmatchingdialogskillspillsectionlabel         : 'We identified the following skills in your CV. To revise this list, update your CV and try again',
	skillmatchingdialogresumeextractionfailed         : 'CV extraction failed. Please try again',
	skillmatchingdialognoskillsfound                  : 'No Skills Found',
	skillmatchingdialognoskillsfoundsubtitle          : 'Use filter options to refine your search',
	skillmatchingdialogdpcslabel                      : 'To continue with skills matching, please accept the consent statement',
	skillmatchingdialogdpcsstatementfetcherror        : 'Error fetching Data Privacy Consent Statement',
	skillmatchingdialoguploaderror                    : 'There is an issue examining your CV. Please try again',
	skillmatchingdialoguploaderror404                 : 'Skills expired. Please upload CV again.',
	skillmatchingdialoguploaderror413                 : 'The CV is too large. Please try again with a smaller file.',
	skillmatchingdialoguploaderror422                 : 'This CV cannot be examined. Please try again with a different file',
	skillmatchingdialoguploaderror400                 : 'The CV name contains invalid characters. Please rename CV and try again',
	skillmatchingdialoguploaderror500                 : 'There is an issue examining your CV. Please try again',
	skillscloudtitlejobskills                         : 'Job Skills',
	skillscloudlabelkeyskills                         : 'Key Skills',
	skillscloudlabelrelevantskills                    : 'Relevant Skills',
	skillscloudskillpaneltext                         : 'Upload Your CV',
	skillscloudskillpanellabel                        : 'Use your CV to see how well your skills match up with this job',
	skillscloudnoskillsmatch                          : 'No skills match your CV.',
	skillscloudfindotherjobstomatchlink               : 'Find other jobs that match your skills.'
};